services:
  nginx:
    ports:
      - "80:80"
    build: ./dockerfiles/nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/plakha.ru.conf:/etc/nginx/conf.d/plakha.ru.conf
      - ./logs/default:/var/log/nginx/
      - ./logs/plakha.ru:/app_plakha.ru/logs
      - ./html:/app_plakha.ru/html
    links:
      - php
    depends_on:
      - php
  php:
    build: ./dockerfiles/php-fpm/
    volumes:
      - ./html:/app_plakha.ru/html
